"""
Prompt templates for report generation
"""

from typing import Dict, Any


def render_report_template(context: Dict[str, Any]) -> str:
    """
    Render report template with context variables
    
    Args:
        context: Dictionary with template variables
            - molecule: Drug/molecule name
            - indication: Disease/indication
            - trial_count: Number of trials found
            - patent_count: Number of patents found
            - fto_risk: Freedom-to-operate risk level
    
    Returns:
        Rendered template string
    """
    
    molecule = context.get("molecule", "Unknown")
    indication = context.get("indication", "Unknown")
    molecule_title = context.get("molecule_title", molecule.title())
    indication_title = context.get("indication_title", indication.title())
    trial_count = context.get("trial_count", 0)
    patent_count = context.get("patent_count", 0)
    fto_risk = context.get("fto_risk", "unknown")
    
    template = f"""
# Drug Repurposing Analysis: {molecule_title} for {indication_title}

## Executive Summary

This report analyzes the drug repurposing opportunity for **{molecule_title}** 
in the treatment of **{indication_title}**.

### Key Findings:
- **Clinical Evidence**: {trial_count} clinical trials identified
- **Patent Landscape**: {patent_count} relevant patents found
- **FTO Risk**: {fto_risk.upper()}

## Methodology

This analysis integrates data from multiple sources:
1. Clinical trial databases (ClinicalTrials.gov)
2. Patent databases (USPTO, EPO, Google Patents)
3. Internal clinical experiment reports
4. Web intelligence and market research
5. Molecular property analysis

## Detailed Analysis

The following sections provide comprehensive analysis across all dimensions
of the drug repurposing opportunity.

---

*This is an automated report generated by the VHS Drug Repurposing Platform.*
*All findings should be validated by domain experts before making strategic decisions.*
"""
    
    return template.strip()
