import { Calendar, Download, Activity } from 'lucide-react';
import { ReportHeader } from '../components/report/ReportHeader';
import { MolecularValidator } from '../components/report/MolecularValidator';
import { Badge } from '../components/ui/Badge';
import { ProgressBar } from '../components/ui/ProgressBar';

const reportData = {
  molecule: 'Metformin',
  date: 'March 23, 2026',
  confidenceScore: 78,
  opportunities: 3,
  summary: 'Metformin demonstrates significant repurposing potential beyond its established use in Type 2 diabetes. Analysis of 47 clinical trials, 12 patents, and extensive real-world evidence suggests compelling opportunities in neurological, oncological, and endocrine indications with manageable FTO risk.',
  repurposingOpportunities: [
    {
      indication: "Alzheimer's Disease",
      priority: 'HIGH' as const,
      evidence: 'Phase II trials ongoing, strong AMPK-mediated neuroprotective mechanistic evidence',
      trialCount: 8,
      confidence: 85
    },
    {
      indication: 'Polycystic Ovary Syndrome',
      priority: 'MEDIUM' as const,
      evidence: 'Multiple approved uses in some markets, strong observational and RCT data',
      trialCount: 12,
      confidence: 70
    },
    {
      indication: 'Colorectal Cancer Prevention',
      priority: 'MEDIUM' as const,
      evidence: 'Phase I trials active, large observational cohort studies support association',
      trialCount: 5,
      confidence: 65
    }
  ],
  patents: [
    { id: 'US10234567', title: 'Metformin compositions for cancer therapy', assignee: 'BioTech Corp', expiry: '2038-07-20', ftoRisk: 'LOW' as const },
    { id: 'US10123456', title: 'Methods for treating neurological conditions', assignee: 'Pharma Inc', expiry: '2035-03-15', ftoRisk: 'LOW' as const },
    { id: 'US10567890', title: 'Metformin extended release formulations', assignee: 'MedChem Ltd', expiry: '2036-11-08', ftoRisk: 'MEDIUM' as const },
    { id: 'US10890123', title: 'Combination therapies with biguanides', assignee: 'Global Pharma', expiry: '2033-04-22', ftoRisk: 'LOW' as const }
  ],
  clinicalPhases: {
    'Phase I': ["Colorectal Cancer"],
    'Phase II': ["Alzheimer's Disease", "Lung Cancer"],
    'Phase III': ["PCOS"],
    'Approved': ["Type 2 Diabetes"]
  },
  molecularValidation: {
    score: 78,
    admet: { absorption: 88, distribution: 72, metabolism: 61, excretion: 85, toxicity: 90 },
    targetProtein: 'AMPK',
    bindingAffinity: '-8.4 kcal/mol'
  },
  recommendations: [
    "Initiate Phase II investigator-sponsored trial for Alzheimer's indication leveraging existing safety data",
    "File 505(b)(2) NDA application using established safety profile to reduce clinical data requirements",
    "Conduct comprehensive FTO analysis specific to Alzheimer's AMPK pathway claims before IP filing"
  ]
};

export const ReportPage = () => {
  return (
    <div className="min-h-screen bg-gray-50 dark:bg-[#0F1117] flex flex-col">
      <ReportHeader 
        molecule={reportData.molecule}
        date={reportData.date}
        score={reportData.confidenceScore}
        opportunities={reportData.opportunities}
      />

      <div className="flex-1 overflow-y-auto w-full">
        <div className="max-w-4xl mx-auto px-4 py-6 md:px-8 md:py-10">
          
          {/* SECTION 1: Title block */}
          <div className="mb-12">
            <h1 className="text-4xl md:text-5xl font-black text-gray-900 dark:text-gray-100 tracking-tight">
              {reportData.molecule}
            </h1>
            <div className="text-gray-500 dark:text-gray-400 mt-2 text-base md:text-lg">
              Innovation Product Story — Drug Repurposing Analysis
            </div>
            <div className="flex items-center gap-3 mt-4 flex-wrap">
              <div className="flex items-center gap-1.5 text-sm text-gray-400">
                <Calendar className="w-4 h-4" />
                {reportData.date}
              </div>
              <div className="w-1 h-1 rounded-full bg-gray-300 dark:bg-gray-600 hidden sm:block" />
              <Badge label={`${reportData.confidenceScore}/100 Confidence`} variant="info" />
              <Badge label={`${reportData.opportunities} Opportunities`} variant="success" />
              <div className="w-1 h-1 rounded-full bg-gray-300 dark:bg-gray-600 hidden sm:block" />
              <div className="text-sm text-gray-400 w-full sm:w-auto">Generated by RepurposeAI</div>
            </div>
          </div>

          {/* SECTION 2: Executive Summary */}
          <div className="mb-12">
            <div className="flex items-center gap-3 mb-6">
              <div className="w-1 h-6 bg-[#E85D24] rounded-full" />
              <h2 className="text-xl font-bold text-gray-900 dark:text-gray-100">Executive Summary</h2>
            </div>
            
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">
              <div className="bg-[#FFF3EE] dark:bg-[#2A1F1A] border border-[#FDDDD0] dark:border-[#4A2E20] rounded-xl p-5 text-center shadow-sm">
                <div className="text-3xl font-black text-[#E85D24]">47</div>
                <div className="text-xs text-gray-500 dark:text-gray-400 uppercase tracking-wide mt-1">Clinical Trials</div>
              </div>
              <div className="bg-[#FFF3EE] dark:bg-[#2A1F1A] border border-[#FDDDD0] dark:border-[#4A2E20] rounded-xl p-5 text-center shadow-sm">
                <div className="text-3xl font-black text-[#E85D24]">12</div>
                <div className="text-xs text-gray-500 dark:text-gray-400 uppercase tracking-wide mt-1">Patents</div>
              </div>
              <div className="bg-[#FFF3EE] dark:bg-[#2A1F1A] border border-[#FDDDD0] dark:border-[#4A2E20] rounded-xl p-5 text-center shadow-sm">
                <div className="text-3xl font-black text-[#E85D24]">3</div>
                <div className="text-xs text-gray-500 dark:text-gray-400 uppercase tracking-wide mt-1">Opportunities</div>
              </div>
            </div>
            <p className="text-gray-600 dark:text-gray-400 leading-relaxed text-sm md:text-base">
              {reportData.summary}
            </p>
          </div>

          {/* SECTION 3: Repurposing Opportunities */}
          <div className="mb-12">
            <div className="flex items-center gap-3 mb-6">
              <div className="w-1 h-6 bg-[#E85D24] rounded-full" />
              <h2 className="text-xl font-bold text-gray-900 dark:text-gray-100">Repurposing Opportunities</h2>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 md:gap-5">
              {reportData.repurposingOpportunities.map((opp, idx) => (
                <div key={idx} className="bg-white dark:bg-[#1E2130] border border-gray-200 dark:border-[#2D3148] rounded-xl p-5 shadow-sm hover:shadow-md transition-shadow flex flex-col">
                  <div className="flex justify-between items-start mb-3">
                    <div className="font-bold text-gray-900 dark:text-gray-100 text-sm leading-tight pr-2">
                      {opp.indication}
                    </div>
                    <Badge 
                      label={opp.priority} 
                      variant={opp.priority === 'HIGH' ? 'danger' : opp.priority === 'MEDIUM' ? 'warning' : 'success'} 
                    />
                  </div>
                  <p className="text-xs text-gray-500 dark:text-gray-400 leading-relaxed mb-4 flex-1">
                    {opp.evidence}
                  </p>
                  <div className="flex items-center gap-1.5 text-xs text-gray-400 mb-3">
                    <Activity className="w-3.5 h-3.5" />
                    {opp.trialCount} active trials
                  </div>
                  <div>
                    <div className="flex justify-between text-xs mb-1.5">
                      <span className="text-gray-400">Confidence</span>
                      <span className="text-[#E85D24] font-semibold">{opp.confidence}%</span>
                    </div>
                    <ProgressBar value={opp.confidence} animated={true} />
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* SECTION 4: Patent Landscape */}
          <div className="mb-12">
            <div className="flex items-center gap-3 mb-6">
              <div className="w-1 h-6 bg-[#E85D24] rounded-full" />
              <h2 className="text-xl font-bold text-gray-900 dark:text-gray-100">Patent Landscape</h2>
            </div>

            <div className="bg-white dark:bg-[#1E2130] border border-gray-200 dark:border-[#2D3148] rounded-xl shadow-sm overflow-x-auto">
              <table className="w-full text-left text-sm min-w-[600px]">
                <thead className="bg-gray-50 dark:bg-[#161927] border-b border-gray-200 dark:border-[#2D3148]">
                  <tr>
                    <th className="px-6 py-3 text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide">Patent ID</th>
                    <th className="px-6 py-3 text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide">Title</th>
                    <th className="px-6 py-3 text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide">Assignee</th>
                    <th className="px-6 py-3 text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide">Expiry Date</th>
                    <th className="px-6 py-3 text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide">FTO Risk</th>
                  </tr>
                </thead>
                <tbody>
                  {reportData.patents.map((pat, idx) => (
                    <tr key={idx} className="hover:bg-gray-50 dark:hover:bg-[#252840] border-b border-gray-100 dark:border-[#2D3148] last:border-0">
                      <td className="px-6 py-4 font-mono text-xs text-[#E85D24]">{pat.id}</td>
                      <td className="px-6 py-4 text-sm text-gray-700 dark:text-gray-300">{pat.title}</td>
                      <td className="px-6 py-4 text-xs text-gray-500">{pat.assignee}</td>
                      <td className="px-6 py-4 text-xs text-gray-500">{pat.expiry}</td>
                      <td className="px-6 py-4">
                        <Badge 
                          label={pat.ftoRisk} 
                          variant={pat.ftoRisk === 'LOW' ? 'success' : pat.ftoRisk === 'MEDIUM' ? 'warning' : 'danger'} 
                        />
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* SECTION 5: Clinical Trials Pipeline */}
          <div className="mb-12">
            <div className="flex items-center gap-3 mb-6">
              <div className="w-1 h-6 bg-[#E85D24] rounded-full" />
              <h2 className="text-xl font-bold text-gray-900 dark:text-gray-100">Clinical Trials Pipeline</h2>
            </div>

            <div className="bg-white dark:bg-[#1E2130] border border-gray-200 dark:border-[#2D3148] rounded-xl p-6 shadow-sm">
              <div className="flex items-start">
                {(Object.entries(reportData.clinicalPhases) as [string, string[]][]).map(([phase, indications], index, array) => {
                  const hasIndications = indications.length > 0;
                  return (
                    <div key={phase} className="flex-1 -mx-2 first:ml-0 last:mr-0">
                      <div className="flex items-center">
                        <div className={`w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold z-10 
                          ${hasIndications ? 'bg-[#E85D24] text-white' : 'bg-gray-200 dark:bg-gray-700 text-gray-400'}`}>
                          {index + 1}
                        </div>
                        {index < array.length - 1 && (
                          <div className={`flex-1 h-0.5 ${hasIndications ? 'bg-[#E85D24]' : 'bg-gray-200 dark:bg-gray-700'}`} />
                        )}
                      </div>
                      
                      <div className="text-xs text-gray-500 mt-2 font-medium">
                        {phase}
                      </div>

                      <div className="mt-3 space-y-1.5 pr-2">
                        {indications.map((ind, idx) => (
                          <div key={idx} className="bg-[#FFF3EE] dark:bg-[#2A1F1A] text-[#E85D24] text-xs rounded-lg px-2.5 py-1.5 text-center border border-[#FDDDD0] dark:border-[#4A2E20]">
                            {ind}
                          </div>
                        ))}
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>

          {/* SECTION 6: Molecular Validation */}
          <div className="mb-12">
            <MolecularValidator 
              score={reportData.molecularValidation.score}
              admet={reportData.molecularValidation.admet}
              targetProtein={reportData.molecularValidation.targetProtein}
              bindingAffinity={reportData.molecularValidation.bindingAffinity}
            />
          </div>

          {/* SECTION 7: Recommendations */}
          <div className="mb-12">
            <div className="flex items-center gap-3 mb-6">
              <div className="w-1 h-6 bg-[#E85D24] rounded-full" />
              <h2 className="text-xl font-bold text-gray-900 dark:text-gray-100">Recommendations</h2>
            </div>

            <div className="space-y-4">
              {reportData.recommendations.map((rec, idx) => (
                <div key={idx} className="flex items-start gap-4 bg-white dark:bg-[#1E2130] border border-gray-200 dark:border-[#2D3148] rounded-xl p-4 shadow-sm">
                  <div className="w-8 h-8 rounded-full bg-[#E85D24] text-white flex items-center justify-center text-sm font-bold flex-shrink-0">
                    {idx + 1}
                  </div>
                  <div className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed pt-1.5">
                    {rec}
                  </div>
                </div>
              ))}
            </div>
          </div>

        </div>

        {/* FOOTER */}
        <div className="border-t border-gray-200 dark:border-[#2D3148] bg-white dark:bg-[#1A1D27] px-8 py-6 mt-10 flex flex-col items-center gap-4">
          <div className="flex flex-col items-center">
            <div className="text-sm text-gray-400 dark:text-gray-500">Generated by RepurposeAI Agentic AI Platform</div>
            <div className="text-xs text-gray-300 dark:text-gray-600 mt-1">Confidential — For Internal Use Only · March 23, 2026</div>
          </div>
          <button className="bg-[#E85D24] hover:bg-[#C94D1A] text-white rounded-lg px-6 py-2.5 text-sm font-medium flex items-center gap-2 mt-2 transition-colors">
            <Download className="w-4 h-4" />
            Download Full PDF
          </button>
        </div>

      </div>
    </div>
  );
};
