from typing import Dict, Any
from utils.llm_utils import get_llm

class ReportGeneratorAgent:
    """Generates comprehensive drug repurposing reports"""
    
    def __init__(self):
        self.llm = get_llm()
    
    async def generate_report(self, state: Dict[str, Any]) -> Dict[str, Any]:
        """Generate comprehensive analysis report"""
        
        # Collect all analysis results
        clinical_analysis = state.get("clinical_trials_analysis", "")
        patent_analysis = state.get("patent_analysis", "")
        regulatory_insights = state.get("regulatory_insights", "")
        web_intelligence = state.get("web_intelligence", "")
        drug_analysis = state.get("drug_analysis", "")
        
        # Generate executive summary
        executive_summary = await self._generate_executive_summary(state)
        
        # Compile full report
        full_report = await self._compile_full_report(
            state, executive_summary, clinical_analysis, 
            patent_analysis, regulatory_insights, web_intelligence, drug_analysis
        )
        
        state["executive_summary"] = executive_summary
        state["report"] = full_report
        state["status"] = "completed"
        
        return state
    
    async def _generate_executive_summary(self, state: Dict[str, Any]) -> str:
        """Generate executive summary of findings"""
        query = state.get("query", "")
        molecule = state.get("molecule", "")
        
        prompt = f"""
        Generate an executive summary for drug repurposing analysis:
        
        Query: {query}
        Molecule: {molecule}
        
        Based on the analysis conducted, provide:
        - Key opportunity assessment (High/Medium/Low potential)
        - Critical success factors
        - Major risks and mitigation strategies
        - Recommended next steps
        - Timeline and resource estimates
        
        Keep it concise (2-3 paragraphs) and actionable for decision makers.
        """
        
        response = await self.llm.ainvoke(prompt)
        return response.content
    
    async def _compile_full_report(self, state: Dict[str, Any], executive_summary: str,
                                 clinical_analysis: str, patent_analysis: str,
                                 regulatory_insights: str, web_intelligence: str, 
                                 drug_analysis: str) -> str:
        """Compile comprehensive report"""
        
        query = state.get("query", "")
        molecule = state.get("molecule", "")
        
        report = f"""
# Drug Repurposing Analysis Report

## Query: {query}
## Molecule: {molecule}

---

## Executive Summary
{executive_summary}

---

## Drug Analysis & Properties
{drug_analysis}

---

## Clinical Trials Analysis
{clinical_analysis}

---

## Patent Landscape & FTO Assessment
{patent_analysis}

---

## Regulatory Insights
{regulatory_insights}

---

## Market Intelligence
{web_intelligence}

---

## Conclusions and Recommendations

Based on the comprehensive analysis above, this drug repurposing opportunity presents a structured pathway for evaluation. Key decision points and next steps have been identified across clinical, regulatory, and commercial dimensions.

*Report generated by VHS Drug Repurposing Platform*
        """
        
        return report.strip()